name: Build and deploy Node.js app to Azure Web App - SportsChatPlus

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Build frontend
        run: |
          cd sportschat-frontend
          npm install
          npm run build
      
      - name: Install backend dependencies
        run: |
          cd sportschat-backend
          npm install
      
      - name: Copy built frontend to backend
        run: |
          cp -r sportschat-frontend/build sportschat-backend/
      
      - name: Create deployment package
        run: |
          cd sportschat-backend
          
          # Create package.json for production
          echo '{
            "name": "sportschat-backend",
            "version": "1.0.0",
            "main": "server.js",
            "engines": {
              "node": "18.x"
            },
            "scripts": {
              "start": "node server.js"
            },
            "dependencies": {
              "axios": "^1.8.4",
              "bcrypt": "^5.1.1",
              "cors": "^2.8.5",
              "dotenv": "^16.4.7",
              "express": "^4.21.2",
              "express-session": "^1.18.1",
              "mssql": "^11.0.1",
              "mysql2": "^3.12.0",
              "socket.io": "^4.8.1"
            }
          }' > package.json
          
          # Zip the deployment package
          zip -r ../release.zip . -x "node_modules/*" ".git/*"
          cd ..
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_59948EF40DD1414B9AE15E300D54DFC3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A9D23C250A9E49E4B514AD57063F3C14 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_104155F6F3A243BEA518D0F5B966ED34 }}
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SportsChatPlus'
          slot-name: 'Production'
          package: .