name: Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    
    - name: Build Frontend
      run: |
        cd sportschat-frontend
        npm install
        npm run build
        cd ..
    
    - name: Copy Frontend Build to Backend
      run: |
        mkdir -p sportschat-backend/build
        cp -r sportschat-frontend/build/* sportschat-backend/build/
    
    - name: Install Backend Dependencies
      run: |
        cd sportschat-backend
        npm install
    
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sportschatplus'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./sportschat-backend